dataset:
  max_points: 16384


model:
  name: centerpoint
  pc_area_scope: [[-40, 40], [-1, 3], [0, 70.4]]
  box_code_cfg: 
    code_size: 7
    encode_angle_by_sincos: True
  in_channels: 4
  use_multihead: True
  use_direction_classifier: False
  cls_weight: 1.0
  reg_weight: 2.0
  dir_weight: 0.2
  pos_cls_weight: 1.0
  neg_cls_weight: 1.0
  dir_offset: 0.785398
  dir_limit_offset: 0.0
  num_dir_bins: 2
  last_kernel_size: 1
  reg_config:
    num_middle_layers: 0
    mid_channels: 64
    reg_list:
      reg: 2
      height: 1
      size: 3
      angle: 2
  rpn_head_configs: [
      {
          'head_cls_name': ['Car', 'Cyclist', 'Pedestrian']
      }
  ]
  backbone_2d_configs: 
    num_channels: [128, 256]
    layer_nums: [5, 5]
    stride: [1, 2]
    up_num_channels: [256, 256]
    up_stride: [1, 2]
  
  loss_cfg:
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]    

  nms_configs:
    roi_threshold: 0.1
    nms_threshold: 0.01
    joint_nms: False
    before_nms_max: 4096
    after_nms_max: 500
  
  regress_ignored_anchors: False
  bn:
    momentum: 0.01
    eps: 0.001

num_epochs: 80
batch_size: 32

criterion:
  name: sigmoid-focal
  gamma: 2.0
  alpha: 0.25

optimizer:
  name: adam_onecycle
  lr: 0.003
  weight_decay: 0.01


scheduler:
  name: onecycle
  momentums: [0.95, 0.85]
  div_factor: 10
  pct_start: 0.4
